### ISSUE TITLE
How to disable template graph?

### ISSUE THREAD

**Issue by jangroth** [aws-cloudformation/cfn-lint-visual-studio-code#181]
... I get this as a default whenever I open a CFN file. 

I don't need to/want to see the graph for every CFN file I open. Also, the `.dot` files make an unwanted appearance in my git index.

I couldn't find a way to disable the functionality...!? 🤔

**Comment by PatMyron** [comment]
From my understanding of https://github.com/aws-cloudformation/cfn-lint-visual-studio-code/pull/106, it should only create `.dot` files when the graph preview pane is opened, and it should delete them when the graph preview pane is closed:


![image](https://user-images.githubusercontent.com/5374887/82874993-a7539f80-9eeb-11ea-888e-ea4cf006ecc2.png)


https://github.com/aws-cloudformation/cfn-lint-visual-studio-code/blob/1cff571e3a5d2e0e77f9826fb403ece7cd9eded0/server/src/server.ts#L174

https://github.com/aws-cloudformation/cfn-lint-visual-studio-code/blob/1cff571e3a5d2e0e77f9826fb403ece7cd9eded0/client/src/extension.ts#L154-L157
