### ISSUE TITLE
cfn-lint doesn't work on my vscode environment

### ISSUE THREAD

**Issue by AditModi** [aws-cloudformation/cfn-lint-visual-studio-code#182]
This may be due to mistakes in my environment.

I did pip install cfn-lint.

installed cloudformation lint extension.

but it doesn't seem to work for me.

any suggestions?

**Comment by PatMyron** [comment]
Is `cfn-lint` in your [`PATH`](https://en.m.wikipedia.org/wiki/PATH_(variable))?

**Comment by AditModi** [comment]
Environment/OS: Windows

`
cfn-lint
`
works on cmd but not on vscode terminal.

what should I be changing ?

**Comment by PatMyron** [comment]
It will also only invoke `cfn-lint` on `.json`/`.yaml` files with either [`AWSTemplateFormatVersion`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html) or [`(AWS|Alexa|Custom)::` resource types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html):
https://github.com/aws-cloudformation/cfn-lint-visual-studio-code/blob/edd51fb86441a1c48d294c4b664189c6f4d11399/server/src/server.ts#L125-L143

**Comment by AditModi** [comment]
For anyone looking for solution to similar problem.
cfn-lint was not working because I had not correctly set up my vscode path.
Now it is working.
