### ISSUE TITLE
How do I ignore certain non-CloudFormation template YAML files from being linted?

### ISSUE THREAD

**Issue by ryancabanas** [aws-cloudformation/cfn-lint-visual-studio-code#233]
In my project I have an OpenAPI file at `/docs/openapi.yaml` and CloudFormation Linter keeps trying to lint the file.  I keep getting an error box in the lower right corner like this.

![image](https://user-images.githubusercontent.com/27093222/189364951-a0bf2b27-12c7-4103-8daf-4c31ca032d2e.png)

When I click the "Go to output" button, the error says, "Don't believe this is a CloudFormation template."

How do I get CloudFormation Linter to ignore this file?

Thanks!

**Comment by kddejong** [comment]
I'll look into this today and try to get this resolved.

**Comment by ryancabanas** [comment]
Thanks!
