### ISSUE TITLE
Request textDocument/hover failed

### ISSUE THREAD

**Issue by sehra** [aws-cloudformation/cfn-lint-visual-studio-code#254]
```
[Error - 10:19:24] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Invalid regular expression: /.*{1,255}/: Nothing to repeat
  Code: -32603 
```
Likely commit: https://github.com/aws-cloudformation/cfn-lint-visual-studio-code/commit/3c39873a395e24bd3f23e1ac29337c806813353a

Broken regex: https://github.com/aws-cloudformation/cfn-lint-visual-studio-code/blob/main/server/schema/resources/aws-ssm-association.json#L116

**Comment by cbackas** [comment]
Started noticing this on Friday, the popup constantly reopening every time you move your mouse over the screen drives me a little insane lol

@kddejong hopefully not too complicated to fix? I know regex is annoying

**Comment by kddejong** [comment]
Looking into it now.  I thought I was getting those filtered out.

**Comment by matthew-heyner** [comment]
I just updated to 0.24.0 and noticed this issue as well. Hopefully we can get a fix soon!

**Comment by cbackas** [comment]
@kddejong Thanks, no more annoying error!

**Comment by SmileF4ce** [comment]
The issue persists for me, even with version v0.24.1.

_Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: e.startsWith is not a function_
  Code: -32603 

A reinstall of the package incl. restart did not resolve the issue.

**Comment by SmileF4ce** [comment]
The issue just occurs in one template file independently of the resource itself. Hovering any resource type in the file causes the problem such as:

- AWS::ElasticLoadBalancingV2::TargetGroup
- AWS::ElasticLoadBalancingV2::LoadBalancer
- AWS::ElasticLoadBalancingV2::Listener
- AWS::AutoScaling::AutoScalingGroup
- AWS::AutoScaling::LaunchConfiguration

I have not had any issues with this file before, it deploys just fine and _cfn-lint_ only returns three warnings (W1020, W2001, W2506).

**Comment by kddejong** [comment]
Do you know what resource types you are hovering on? Or what resource types are in the template?

**Comment by kddejong** [comment]
`e.startsWith` seems to be part of parsing enums in the schema files.  There was an issue in the `1.0.9` version of `yaml-language-server` with number based enums.  I'm going to update our dependencies to `1.10.0` and see if that helps fixes the issue.  For some reason I'm having troubles replicating the issue but trying all the options to replicate

**Comment by kddejong** [comment]
https://github.com/redhat-developer/yaml-language-server/pull/750 here is the issue

**Comment by Hoshock** [comment]
Thanks for your comment! I'll comment after the update.

**Comment by Hoshock** [comment]
I've found the problem has been solved. Thanks for your update.
