### ISSUE TITLE
AWS lambda Runtime: "nodejs18.x" support

### ISSUE THREAD

**Issue by straimtheone** [aws-cloudformation/cfn-lint-visual-studio-code#305]
The current "base.schema.json" has not been updated to support the "nodejs18.x" lambda runtime even though is currently AWS recommended runtime version (as they finally bundled it with the AWS SDK for JavaScript v3).

Current error message:
[cfn-lint] E3030: You must specify a valid value for Runtime (nodejs18.x). Valid values are ["dotnet6", "dotnetcore1.0", "dotnetcore2.0", "dotnetcore2.1", "dotnetcore3.1", "go1.x", "java11", "java8", "java8.al2", "nodejs", "nodejs10.x", "nodejs12.x", "nodejs14.x", "nodejs16.x", "nodejs4.3", "nodejs4.3-edge", "nodejs6.10", "nodejs8.10", "provided", "provided.al2", "python2.7", "python3.6", "python3.7", "python3.8", "python3.9", "ruby2.5", "ruby2.7"]

https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html?icmpid=docs_lambda_rss

**Comment by kddejong** [comment]
cfn-lint is used for validation.  Make sure to update it using `pip install --upgrade cfn-lint`
