### ISSUE TITLE
Add AWS Shield Advanced support

### ISSUE THREAD

**Issue by spedersen-emailage** [aws-cloudformation/cfn-lint-visual-studio-code#318]
AWS Shield Advanced support was added to CloudFormation on 2023-05-30. 

https://aws.amazon.com/about-aws/whats-new/2023/05/aws-shield-advanced-cloudformation/
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_Shield.html

v0.24.5 was released 2023-05-01, so it does not yet support the new resources:

* `AWS::Shield::DRTAccess`
* `AWS::Shield::ProactiveEngagement`
* `AWS::Shield::Protection`
* `AWS::Shield::ProtectionGroup`

Much appreciated!

**Comment by spedersen-emailage** [comment]
Any update on this? Thanks!

**Comment by spedersen-emailage** [comment]
When can we expect the updated CFN model to be incorporated into cnf-lint?

**Comment by kddejong** [comment]
vscode plugin is https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint

that plugin will run cfn-lint and provide the errors.
https://github.com/aws-cloudformation/cfn-lint/releases

You need to update cfn-lint using pip `pip install --upgrade cfn-lint`

**Comment by spedersen-emailage** [comment]
Missed that part, thanks!
