### ISSUE TITLE
AWS::Lambda::EventSourceMapping not recognizing a SQS as a valid Ref to resources

### ISSUE THREAD

**Issue by richardwhiteii** [aws-cloudformation/cfn-lint-visual-studio-code#329]
"LambdaSQSEventSource": {
        "Type": "AWS::Lambda::EventSourceMapping",
        "Properties": {
          "EventSourceArn": {
            **"_Ref_":** "DataNewQueue"  //The line showing as red.
          },
          "FunctionName": {
            "Ref": "SecureLambdaFunction"
          },
          "Enabled": true,
          "BatchSize": 5
        }
      },

**Comment by kddejong** [comment]
@richardwhiteii Should be using `"Fn::GetAtt": ["DataNewQueue", "Arn"]`

**Comment by richardwhiteii** [comment]
Thank you
