### ISSUE TITLE
Support for Transform: 'AWS::LanguageExtensions'

### ISSUE THREAD

**Issue by KobiShikly** [aws-cloudformation/cfn-lint-visual-studio-code#365]
Linter does not honor the Transform reference at the begining of the template:
Transform: 'AWS::LanguageExtensions'

i.e., if using the function !FindInMap with a default value (4th value) then we get an error:
E1011: FindInMap is a list with 3 values for Resources/..

See AWS Cloudformation documentation regarding [FindInMap function enhanements](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-findinmap-enhancements.html):

I'm using CloudFormation Linter v0.25.2

**Comment by kddejong** [comment]
This plugin is an integration into the cli tool [cfn-lint](https://github.com/aws-cloudformation/cfn-lint).  Support is integrated into cfn-lint you will need to update to take advantage of the LanguageExtensions.  The newest version of the plugin should alert you when you are using an outdated version of cfn-lint.
