### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by harishs-cg** [aws-cloudformation/cfn-lint-visual-studio-code#375]
I have verified from the terminal to check if linting works and it does.
Adding the path to vscode settings also doesn't change anything.

**Comment by ethanengland** [comment]
Same issue here

**Comment by kddejong** [comment]
In your Output tab there is a pull down for CloudFormation linter Language Server.  Can you provide a redacted version of the log?

**Comment by harishs-cg** [comment]
> In your Output tab there is a pull down for CloudFormation linter Language Server. Can you provide a redacted version of the log?

`The language client requires VS Code version ^1.82.0 but received version 1.81.0`

Looks like the fix was obvious. It worked.
