### ISSUE TITLE
Lambda Runtime Update

### ISSUE THREAD

**Issue by tmthbrunner** [aws-cloudformation/cfn-lint-visual-studio-code#377]
cfn-lint does not recognize anything newer than Python 3.9 when defining Lambda Runtimes

**Comment by kddejong** [comment]
This plugin provides an integration into https://github.com/aws-cloudformation/cfn-lint.  We do have notifications now when launching vscode if you are behind in cfn-lint.  You'll want to do an upgrade of cfn-lint and this should hopefully resolve itself for you

**Comment by tmthbrunner** [comment]
My bad. cfn-lint was out of date.
