### ISSUE TITLE
Upload to Open VSX

### ISSUE THREAD

**Issue by albertodiazdorado** [aws-cloudformation/cfn-lint-visual-studio-code#392]
Users of VS Code in Arch Linux (or Manjaro) pull the extensions from Open VSX [1] and not from the regular VS Code extensions marketplace. If an extension is not available in Open VSX, I only got two options (both bad):

1. Download the extension as a `.vsix` file and install it from there
2. Forfeit the Arch Linux open source release "Code - OSS" and go for the Microsoft-branded release [2]

Hence: Would it be possible to submit this extension to Open VSX?

`cfn-lint-visual-studio-code` is unmatched right now and we do not have anything similar in Open VSX. Since it is licensed under `Apache 2.0`, I can always go ahead, fork this repository and submit the extension myself to Open VSX -- however, I thought that I would ask first whether any of the maintainers would like to it themselves.

---
[1] https://open-vsx.org/
[2] https://wiki.archlinux.org/title/Visual_Studio_Code

**Comment by kddejong** [comment]
https://open-vsx.org/extension/kddejong/vscode-cfn-lint

**Comment by albertodiazdorado** [comment]
Thank you so much @kddejong !!
