### ISSUE TITLE
Errors on yaml.validate: true

### ISSUE THREAD

**Issue by riccardopedrielli** [aws-cloudformation/cfn-lint-visual-studio-code#97]
### Environment:

- macOS
- cfn-lint: 0.29.5
- vs code: 1.44.2
- vscode-cfn-lint: 0.11.1
- vscode-yaml: 0.7.2
- no other yaml extension installed

### Problem

This extension is setting `yaml.validate` to `false` whenever it starts. 
As I understand this is done because, with the default setting (`true`), a lot of false errors are shown.

Leaving out that's a bad practice to edit other extension's settings with no user consent/notice, my first question is:

- Why disabling the validation instead of fixing the bug?

I noticed other closed issues on this topic, but it seems the problem was never resolved.
Since I think that we should be able to work with the validation enabled, I want to ask:

- Will there ever be an effort to make this extension work with `yaml.validate: true`?

**Comment by kddejong** [comment]
Let me test a few things out.
Also note that the Readme needs to be updated to include the setting.
https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/blob/master/package.json#L87-L91

The idea here is to draw visibility to issues with the yaml validation as we are mostly looking to use that extension for the autocomplete capabilities.  We tried to wrap the setting with our own setting and only set it if appropriate.  I would agree this isn't an ideal solution but we believe the autcomplete functionality is helpful to doing CloudFormation development.  What I want to make sure is that we didn't miss a scenario.  We should only be setting `yaml.validate` to `false` only if you have `cfnLint.validateUsingJsonSchema` set to `false`

**Comment by riccardopedrielli** [comment]
Another problem of writing `yaml.validate: false` into the settings.json of vs code is also that the validation is disabled for every other yaml file, be it a cfn o just a regular yaml.

**Comment by PatMyron** [comment]
relevant code:
https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/blob/089b197e2c7df4ec26d35c23ebb77383c724a86e/client/src/extension.ts#L188-L209

**Comment by motdde** [comment]
Hello @kddejong and @PatMyron,

Have you been able to find a solution to this?

I am new to cloud formation. I have spent several hours figuring out why block scalars are flagged as errors in the Yaml files. JSON schema is not identifying values as strings when working with the Intrinsic function.

**Comment by kddejong** [comment]
I'm working on a new way to include the yaml language server that should resolve these issues.  its a bigger rewrite to the plugin but should allow us to completely decouple from the vscode-yaml extension.

**Comment by kddejong** [comment]
We no longer require `vscode-yaml` and this should be resolved at this point.

**Comment by motdde** [comment]
Thanks @kddejong
